name: flutter_apns
description: APNS push notification plugin. Uses firebase_messaging on Android, but replaces it on iOS with custom implementation.
version: 1.2.0
homepage: https://github.com/mwaylabs/flutter-apns

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging:
    git:
      url: https://github.com/kamlesh9070/flutterfire
      path: packages/firebase_messaging
      #path: D:\Projects\Github projects\Flutter\Notification_Projects\akflutterfire\packages\firebase_messaging
      #ref: akfb

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.mwaysolutions.flutter.apns
    pluginClass: FlutterApnsPlugin

